// <auto-generated />
using System;
using MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Migrations
{
    [DbContext(typeof(MetaDataDatabaseContext))]
    [Migration("20200919180105_Adding Few Country Details")]
    partial class AddingFewCountryDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Continent", b =>
                {
                    b.Property<string>("ContinentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentCode");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            ContinentCode = "AF",
                            ContinentName = "Africa"
                        },
                        new
                        {
                            ContinentCode = "AN",
                            ContinentName = "Antarctica"
                        },
                        new
                        {
                            ContinentCode = "AS",
                            ContinentName = "Asia"
                        },
                        new
                        {
                            ContinentCode = "EU",
                            ContinentName = "Europe"
                        },
                        new
                        {
                            ContinentCode = "NA",
                            ContinentName = "North America"
                        },
                        new
                        {
                            ContinentCode = "OC",
                            ContinentName = "Oceania"
                        },
                        new
                        {
                            ContinentCode = "SA",
                            ContinentName = "South America"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CallingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContinentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrthographicMap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryCode");

                    b.HasIndex("ContinentCode");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryCode = "DZ",
                            CallingCode = "+213",
                            Capital = "Algiers",
                            ContinentCode = "AF",
                            CountryName = "Algeria",
                            CurrencyCode = "DZD",
                            Flag = "/wikimedia/countries/flags/dz.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/dz.svg"
                        },
                        new
                        {
                            CountryCode = "AO",
                            CallingCode = "+244",
                            Capital = "Luanda",
                            ContinentCode = "AF",
                            CountryName = "Angola",
                            CurrencyCode = "AOA",
                            Flag = "/wikimedia/countries/flags/ao.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ao.svg"
                        },
                        new
                        {
                            CountryCode = "BJ",
                            CallingCode = "+229",
                            Capital = "Porto-Novo",
                            ContinentCode = "AF",
                            CountryName = "Benin",
                            CurrencyCode = "XOF",
                            Flag = "/wikimedia/countries/flags/bj.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/bj.svg"
                        },
                        new
                        {
                            CountryCode = "BW",
                            CallingCode = "+267",
                            Capital = "Gaborone",
                            ContinentCode = "AF",
                            CountryName = "Botswana",
                            CurrencyCode = "BWP",
                            Flag = "/wikimedia/countries/flags/bw.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/bw.svg"
                        },
                        new
                        {
                            CountryCode = "BF",
                            CallingCode = "+226",
                            Capital = "Ouagadougou",
                            ContinentCode = "AF",
                            CountryName = "Burkina Faso",
                            CurrencyCode = "XOF",
                            Flag = "/wikimedia/countries/flags/bf.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/bf.svg"
                        },
                        new
                        {
                            CountryCode = "BI",
                            CallingCode = "+257",
                            Capital = "Gitega",
                            ContinentCode = "AF",
                            CountryName = "Burundi",
                            CurrencyCode = "BIF",
                            Flag = "/wikimedia/countries/flags/bi.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/bi.svg"
                        },
                        new
                        {
                            CountryCode = "CM",
                            CallingCode = "+237",
                            Capital = "Yaoundé",
                            ContinentCode = "AF",
                            CountryName = "Cameroon",
                            CurrencyCode = "XAF",
                            Flag = "/wikimedia/countries/flags/cm.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/cm.svg"
                        },
                        new
                        {
                            CountryCode = "CV",
                            CallingCode = " +238",
                            Capital = "Praia",
                            ContinentCode = "AF",
                            CountryName = "Cape Verde",
                            CurrencyCode = "CVE",
                            Flag = " / wikimedia/countries/flags/cv.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/cv.svg"
                        },
                        new
                        {
                            CountryCode = "CF",
                            CallingCode = "+236",
                            Capital = "Bangui",
                            ContinentCode = "AF",
                            CountryName = "Central African Republic",
                            CurrencyCode = "XAF",
                            Flag = " / wikimedia/countries/flags/cf.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/cf.svg"
                        },
                        new
                        {
                            CountryCode = "TD",
                            CallingCode = "+235",
                            Capital = "N'Djamena",
                            ContinentCode = "AF",
                            CountryName = "Chad",
                            CurrencyCode = "XAF",
                            Flag = " / wikimedia/countries/flags/td.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/td.svg"
                        },
                        new
                        {
                            CountryCode = "KM",
                            CallingCode = "+269",
                            Capital = "Moroni",
                            ContinentCode = "AF",
                            CountryName = "Comoros",
                            CurrencyCode = "KMF",
                            Flag = "/wikimedia/countries/flags/km.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/km.svg"
                        },
                        new
                        {
                            CountryCode = "CG",
                            CallingCode = "+242",
                            Capital = "Brazzaville",
                            ContinentCode = "AF",
                            CountryName = "Republic of the Congo",
                            CurrencyCode = "XAF",
                            Flag = "/wikimedia/countries/flags/cg.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/cg.svg"
                        },
                        new
                        {
                            CountryCode = "CD",
                            CallingCode = "+243",
                            Capital = "Kinshasa",
                            ContinentCode = "AF",
                            CountryName = "Democratic Republic of the Congo",
                            CurrencyCode = "CDF",
                            Flag = "/wikimedia/countries/flags/cd.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/cd.svg"
                        },
                        new
                        {
                            CountryCode = "CI",
                            CallingCode = "+225",
                            Capital = "Yamoussoukro",
                            ContinentCode = "AF",
                            CountryName = "Ivory Coast",
                            CurrencyCode = "XOF",
                            Flag = "/wikimedia/countries/flags/ci.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ci.svg"
                        },
                        new
                        {
                            CountryCode = "DJ",
                            CallingCode = "+253",
                            Capital = "Djibouti",
                            ContinentCode = "AF",
                            CountryName = "Djibouti",
                            CurrencyCode = "DJF",
                            Flag = "/wikimedia/countries/flags/dj.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/dj.svg"
                        },
                        new
                        {
                            CountryCode = "EG",
                            CallingCode = "+20",
                            Capital = "Cairo",
                            ContinentCode = "AF",
                            CountryName = "Egypt",
                            CurrencyCode = "EGP",
                            Flag = "/wikimedia/countries/flags/eg.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/eg.svg"
                        },
                        new
                        {
                            CountryCode = "GQ",
                            CallingCode = "+240",
                            Capital = "Malabo",
                            ContinentCode = "AF",
                            CountryName = "Equatorial Guinea",
                            CurrencyCode = "XAF",
                            Flag = "/wikimedia/countries/flags/gq.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/gq.svg"
                        },
                        new
                        {
                            CountryCode = "ER",
                            CallingCode = "+291",
                            Capital = "Asmara",
                            ContinentCode = "AF",
                            CountryName = "Eritrea",
                            CurrencyCode = "ERN",
                            Flag = "/wikimedia/countries/flags/er.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/er.svg"
                        },
                        new
                        {
                            CountryCode = "ET",
                            CallingCode = "+251",
                            Capital = "Addis Ababa",
                            ContinentCode = "AF",
                            CountryName = "Ethiopia",
                            CurrencyCode = "ETB",
                            Flag = "/wikimedia/countries/flags/et.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/et.svg"
                        },
                        new
                        {
                            CountryCode = "GA",
                            CallingCode = "+241",
                            Capital = "Libreville",
                            ContinentCode = "AF",
                            CountryName = "Gabon",
                            CurrencyCode = "XAF",
                            Flag = "/wikimedia/countries/flags/ga.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ga.svg"
                        },
                        new
                        {
                            CountryCode = "GM",
                            CallingCode = "+220",
                            Capital = "Banjul",
                            ContinentCode = "AF",
                            CountryName = "The Gambia",
                            CurrencyCode = "GMD",
                            Flag = "/wikimedia/countries/flags/gm.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/gm.svg"
                        },
                        new
                        {
                            CountryCode = "GH",
                            CallingCode = "+233",
                            Capital = "Accra",
                            ContinentCode = "AF",
                            CountryName = "Ghana",
                            CurrencyCode = "GHS",
                            Flag = "/wikimedia/countries/flags/gh.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/gh.svg"
                        },
                        new
                        {
                            CountryCode = "GN",
                            CallingCode = "+224",
                            Capital = "Conakry",
                            ContinentCode = "AF",
                            CountryName = "Guinea",
                            CurrencyCode = "GNF",
                            Flag = "/wikimedia/countries/flags/gn.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/gn.svg"
                        },
                        new
                        {
                            CountryCode = "GW",
                            CallingCode = "+245",
                            Capital = "Bissau",
                            ContinentCode = "AF",
                            CountryName = "Guinea-Bissau",
                            CurrencyCode = "XOF",
                            Flag = "/wikimedia/countries/flags/gw.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/gw.svg"
                        },
                        new
                        {
                            CountryCode = "KE",
                            CallingCode = "+254",
                            Capital = "Nairobi",
                            ContinentCode = "AF",
                            CountryName = "Kenya",
                            CurrencyCode = "KES",
                            Flag = "/wikimedia/countries/flags/ke.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ke.svg"
                        },
                        new
                        {
                            CountryCode = "LS",
                            CallingCode = "+266",
                            Capital = "Maseru",
                            ContinentCode = "AF",
                            CountryName = "Lesotho",
                            CurrencyCode = "LSL",
                            Flag = "/wikimedia/countries/flags/ls.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ls.svg"
                        },
                        new
                        {
                            CountryCode = "LR",
                            Capital = "Monrovia",
                            ContinentCode = "AF",
                            CountryName = "Liberia",
                            Flag = "/wikimedia/countries/flags/lr.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/lr.svg"
                        },
                        new
                        {
                            CountryCode = "LY",
                            CallingCode = "+218",
                            Capital = "Tripoli",
                            ContinentCode = "AF",
                            CountryName = "Libya",
                            CurrencyCode = "LYD",
                            Flag = "/wikimedia/countries/flags/ly.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ly.svg"
                        },
                        new
                        {
                            CountryCode = "MG",
                            CallingCode = "+261",
                            Capital = "Antananarivo",
                            ContinentCode = "AF",
                            CountryName = "Madagascar",
                            CurrencyCode = "MGA",
                            Flag = "/wikimedia/countries/flags/mg.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/mg.svg"
                        },
                        new
                        {
                            CountryCode = "MW",
                            CallingCode = "+265",
                            Capital = "Lilongwe",
                            ContinentCode = "AF",
                            CountryName = "Malawi",
                            CurrencyCode = "MWK",
                            Flag = "/wikimedia/countries/flags/mw.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/mw.svg"
                        },
                        new
                        {
                            CountryCode = "ML",
                            CallingCode = "+223",
                            Capital = "Bamako",
                            ContinentCode = "AF",
                            CountryName = "Mali",
                            CurrencyCode = "XOF",
                            Flag = "/wikimedia/countries/flags/ml.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ml.svg"
                        },
                        new
                        {
                            CountryCode = "MR",
                            CallingCode = "+222",
                            Capital = "Nouakchott",
                            ContinentCode = "AF",
                            CountryName = "Mauritania",
                            CurrencyCode = "MRU",
                            Flag = "/wikimedia/countries/flags/mr.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/mr.svg"
                        },
                        new
                        {
                            CountryCode = "MU",
                            CallingCode = "+230",
                            Capital = "Port Louis",
                            ContinentCode = "AF",
                            CountryName = "Mauritius",
                            CurrencyCode = "MUR",
                            Flag = "/wikimedia/countries/flags/mu.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/mu.svg"
                        },
                        new
                        {
                            CountryCode = "MA",
                            CallingCode = "+212",
                            Capital = "Rabat",
                            ContinentCode = "AF",
                            CountryName = "Morocco",
                            CurrencyCode = "MAD",
                            Flag = "/wikimedia/countries/flags/ma.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ma.svg"
                        },
                        new
                        {
                            CountryCode = "MZ",
                            CallingCode = "+258",
                            Capital = "Maputo",
                            ContinentCode = "AF",
                            CountryName = "Mozambique",
                            CurrencyCode = "MZN",
                            Flag = "/wikimedia/countries/flags/mz.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/mz.svg"
                        },
                        new
                        {
                            CountryCode = "NA",
                            CallingCode = "+264",
                            Capital = "Windhoek",
                            ContinentCode = "AF",
                            CountryName = "Namibia",
                            CurrencyCode = "NAD",
                            Flag = "/wikimedia/countries/flags/na.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/na.svg"
                        },
                        new
                        {
                            CountryCode = "NE",
                            CallingCode = "+227",
                            Capital = "Niamey",
                            ContinentCode = "AF",
                            CountryName = "Niger",
                            CurrencyCode = "XOF",
                            Flag = "/wikimedia/countries/flags/ne.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ne.svg"
                        },
                        new
                        {
                            CountryCode = "NG",
                            CallingCode = "+234",
                            Capital = "Abuja",
                            ContinentCode = "AF",
                            CountryName = "Nigeria",
                            CurrencyCode = "NGN",
                            Flag = "/wikimedia/countries/flags/ng.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ng.svg"
                        },
                        new
                        {
                            CountryCode = "RW",
                            CallingCode = "+250",
                            Capital = "Kigali",
                            ContinentCode = "AF",
                            CountryName = "Rwanda",
                            CurrencyCode = "RWF",
                            Flag = "/wikimedia/countries/flags/rw.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/rw.svg"
                        },
                        new
                        {
                            CountryCode = "ST",
                            CallingCode = "+239",
                            Capital = "São Tomé",
                            ContinentCode = "AF",
                            CountryName = "São Tomé and Príncipe",
                            CurrencyCode = "STN",
                            Flag = "/wikimedia/countries/flags/st.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/st.svg"
                        },
                        new
                        {
                            CountryCode = "SN",
                            CallingCode = "+221",
                            Capital = "Dakar",
                            ContinentCode = "AF",
                            CountryName = "Senegal",
                            CurrencyCode = "XOF",
                            Flag = "/wikimedia/countries/flags/sn.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/sn.svg"
                        },
                        new
                        {
                            CountryCode = "SC",
                            CallingCode = "+248",
                            Capital = "Victoria",
                            ContinentCode = "AF",
                            CountryName = "Seychelles",
                            CurrencyCode = "SCR",
                            Flag = "/wikimedia/countries/flags/sc.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/sc.svg"
                        },
                        new
                        {
                            CountryCode = "SL",
                            CallingCode = "+232",
                            Capital = "Freetown",
                            ContinentCode = "AF",
                            CountryName = "Sierra Leone",
                            CurrencyCode = "SLL",
                            Flag = "/wikimedia/countries/flags/sl.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/sl.svg"
                        },
                        new
                        {
                            CountryCode = "SO",
                            CallingCode = "+252",
                            Capital = "Mogadishu",
                            ContinentCode = "AF",
                            CountryName = "Somalia",
                            CurrencyCode = "SOS",
                            Flag = "/wikimedia/countries/flags/so.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/so.svg"
                        },
                        new
                        {
                            CountryCode = "ZA",
                            CallingCode = "+27",
                            Capital = "Pretoria",
                            ContinentCode = "AF",
                            CountryName = "South Africa",
                            CurrencyCode = "ZAR",
                            Flag = "/wikimedia/countries/flags/za.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/za.svg"
                        },
                        new
                        {
                            CountryCode = "SS",
                            CallingCode = "+211",
                            Capital = "Juba",
                            ContinentCode = "AF",
                            CountryName = "South Sudan",
                            CurrencyCode = "SSP",
                            Flag = "/wikimedia/countries/flags/ss.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ss.svg"
                        },
                        new
                        {
                            CountryCode = "SD",
                            CallingCode = "+249",
                            Capital = "Khartoum",
                            ContinentCode = "AF",
                            CountryName = "Sudan",
                            CurrencyCode = "SDG",
                            Flag = "/wikimedia/countries/flags/sd.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/sd.svg"
                        },
                        new
                        {
                            CountryCode = "SZ",
                            CallingCode = "+268",
                            Capital = "Mbabane",
                            ContinentCode = "AF",
                            CountryName = "Swaziland",
                            CurrencyCode = "ZAR",
                            Flag = "/wikimedia/countries/flags/sz.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/sz.svg"
                        },
                        new
                        {
                            CountryCode = "TZ",
                            CallingCode = "+255",
                            Capital = "Dodoma",
                            ContinentCode = "AF",
                            CountryName = "Tanzania",
                            CurrencyCode = "TZS",
                            Flag = "/wikimedia/countries/flags/tz.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/tz.svg"
                        },
                        new
                        {
                            CountryCode = "TG",
                            CallingCode = "+228",
                            Capital = "Lome",
                            ContinentCode = "AF",
                            CountryName = "Togo",
                            CurrencyCode = "XOF",
                            Flag = "/wikimedia/countries/flags/tg.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/tg.svg"
                        },
                        new
                        {
                            CountryCode = "TN",
                            CallingCode = "+216",
                            Capital = "Tunis",
                            ContinentCode = "AF",
                            CountryName = "Tunisia",
                            CurrencyCode = "TND",
                            Flag = "/wikimedia/countries/flags/tn.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/tn.svg"
                        },
                        new
                        {
                            CountryCode = "UG",
                            CallingCode = "+256",
                            Capital = "Kampala",
                            ContinentCode = "AF",
                            CountryName = "Uganda",
                            CurrencyCode = "UGX",
                            Flag = "/wikimedia/countries/flags/ug.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/ug.svg"
                        },
                        new
                        {
                            CountryCode = "EH",
                            CallingCode = "+212",
                            Capital = "El Aaiún",
                            ContinentCode = "AF",
                            CountryName = "Western Sahara",
                            CurrencyCode = "MAD",
                            Flag = "/wikimedia/countries/flags/eh.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/eh.svg"
                        },
                        new
                        {
                            CountryCode = "ZM",
                            CallingCode = "+260",
                            Capital = "Lusaka",
                            ContinentCode = "AF",
                            CountryName = "Zambia",
                            CurrencyCode = "ZMW",
                            Flag = "/wikimedia/countries/flags/zm.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/zm.svg"
                        },
                        new
                        {
                            CountryCode = "ZW",
                            CallingCode = "+263",
                            Capital = "Harare",
                            ContinentCode = "AF",
                            CountryName = "Zimbabwe",
                            Flag = "/wikimedia/countries/flags/zw.svg",
                            OrthographicMap = "/wikimedia/countries/orthographic-maps/zw.svg"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Currency", b =>
                {
                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BaseNumber")
                        .HasColumnType("int");

                    b.Property<string>("FractionalUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyCode");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            CurrencyCode = "AED",
                            BaseNumber = 100,
                            FractionalUnit = "Fils",
                            Name = "United Arab Emirates dirham",
                            Symbol = "د.إ"
                        },
                        new
                        {
                            CurrencyCode = "AFN",
                            BaseNumber = 100,
                            FractionalUnit = "Pul",
                            Name = "Afghan afghani",
                            Symbol = "؋"
                        },
                        new
                        {
                            CurrencyCode = "ALL",
                            BaseNumber = 100,
                            FractionalUnit = "Qindarkë",
                            Name = "Albanian lek",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyCode = "AMD",
                            BaseNumber = 100,
                            FractionalUnit = "Luma",
                            Name = "Armenian dram",
                            Symbol = "֏"
                        },
                        new
                        {
                            CurrencyCode = "ANG",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Netherlands Antillean guilder",
                            Symbol = "ƒ"
                        },
                        new
                        {
                            CurrencyCode = "AOA",
                            BaseNumber = 100,
                            FractionalUnit = "Cêntimo",
                            Name = "Angolan kwanza",
                            Symbol = "Kz"
                        },
                        new
                        {
                            CurrencyCode = "ARS",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Argentine peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "AUD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Australian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "AWG",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Aruban florin",
                            Symbol = "ƒ"
                        },
                        new
                        {
                            CurrencyCode = "AZN",
                            BaseNumber = 100,
                            FractionalUnit = "Qəpik",
                            Name = "Azerbaijani manat",
                            Symbol = "₼"
                        },
                        new
                        {
                            CurrencyCode = "BAM",
                            BaseNumber = 100,
                            FractionalUnit = "Fening",
                            Name = "Bosnia and Herzegovina convertible mark",
                            Symbol = "KM"
                        },
                        new
                        {
                            CurrencyCode = "BBD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Barbadian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "BDT",
                            BaseNumber = 100,
                            FractionalUnit = "Poisha",
                            Name = "Bangladeshi taka",
                            Symbol = "৳"
                        },
                        new
                        {
                            CurrencyCode = "BGN",
                            BaseNumber = 100,
                            FractionalUnit = "Stotinka",
                            Name = "Bulgarian lev",
                            Symbol = "лв."
                        },
                        new
                        {
                            CurrencyCode = "BHD",
                            BaseNumber = 1000,
                            FractionalUnit = "Fils",
                            Name = "Bahraini dinar",
                            Symbol = ".د.ب"
                        },
                        new
                        {
                            CurrencyCode = "BIF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Burundian franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyCode = "BMD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Bermudian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "BND",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Brunei dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "BOB",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Bolivian boliviano",
                            Symbol = "Bs."
                        },
                        new
                        {
                            CurrencyCode = "BRL",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Brazilian real",
                            Symbol = "R$"
                        },
                        new
                        {
                            CurrencyCode = "BSD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Bahamian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "BTN",
                            BaseNumber = 100,
                            FractionalUnit = "Chetrum",
                            Name = "Bhutanese ngultrum",
                            Symbol = "Nu."
                        },
                        new
                        {
                            CurrencyCode = "BWP",
                            BaseNumber = 100,
                            FractionalUnit = "Thebe",
                            Name = "Botswana pula",
                            Symbol = "P"
                        },
                        new
                        {
                            CurrencyCode = "BYN",
                            BaseNumber = 100,
                            FractionalUnit = "Kapyeyka",
                            Name = "Belarusian ruble",
                            Symbol = "Br"
                        },
                        new
                        {
                            CurrencyCode = "BZD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Belize dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "CAD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Canadian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "CDF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Congolese franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyCode = "CHF",
                            BaseNumber = 100,
                            FractionalUnit = "Rappen",
                            Name = "Swiss franc",
                            Symbol = "Fr."
                        },
                        new
                        {
                            CurrencyCode = "CLP",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Chilean peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "CNY",
                            BaseNumber = 10,
                            FractionalUnit = "Jiao",
                            Name = "Chinese yuan",
                            Symbol = "¥"
                        },
                        new
                        {
                            CurrencyCode = "CKD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Cook Islands dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "COP",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Colombian peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "CRC",
                            BaseNumber = 100,
                            FractionalUnit = "Céntimo",
                            Name = "Costa Rican colón",
                            Symbol = "₡"
                        },
                        new
                        {
                            CurrencyCode = "CUC",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Cuban convertible peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "CVE",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Cape Verdean escudo",
                            Symbol = "Esc"
                        },
                        new
                        {
                            CurrencyCode = "CUP",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Cuban peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "CZK",
                            BaseNumber = 100,
                            FractionalUnit = "Haléř",
                            Name = "Czech koruna",
                            Symbol = "Kč"
                        },
                        new
                        {
                            CurrencyCode = "DJF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Djiboutian franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyCode = "DZD",
                            BaseNumber = 100,
                            FractionalUnit = "Santeem",
                            Name = "Algerian dinar",
                            Symbol = "د.ج"
                        },
                        new
                        {
                            CurrencyCode = "DKK",
                            BaseNumber = 100,
                            FractionalUnit = "Øre",
                            Name = "Danish krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = "DOP",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Dominican peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "EGP",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Egyptian pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = "ERN",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Eritrean nakfa",
                            Symbol = "Nfk"
                        },
                        new
                        {
                            CurrencyCode = "ETB",
                            BaseNumber = 100,
                            FractionalUnit = "Santim",
                            Name = "Ethiopian birr",
                            Symbol = "Br"
                        },
                        new
                        {
                            CurrencyCode = "EUR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            CurrencyCode = "FKP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Falkland Islands pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = "FOK",
                            BaseNumber = 100,
                            FractionalUnit = "Oyra",
                            Name = "Faroese króna",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = "FJD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Fijian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "GBP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "British pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = "GGP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Guernsey pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = "GEL",
                            BaseNumber = 100,
                            FractionalUnit = "Tetri",
                            Name = "Georgian lari",
                            Symbol = "₾"
                        },
                        new
                        {
                            CurrencyCode = "GMD",
                            BaseNumber = 100,
                            FractionalUnit = "Butut",
                            Name = "Gambian dalasi",
                            Symbol = "D"
                        },
                        new
                        {
                            CurrencyCode = "GHS",
                            BaseNumber = 100,
                            FractionalUnit = "Pesewa",
                            Name = "Ghanaian cedi",
                            Symbol = "₵"
                        },
                        new
                        {
                            CurrencyCode = "GIP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Gibraltar pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = "GNF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Guinean franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyCode = "GTQ",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Guatemalan quetzal",
                            Symbol = "Q"
                        },
                        new
                        {
                            CurrencyCode = "GYD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Guyanese dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "HNL",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Honduran lempira",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyCode = "HKD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Hong Kong dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "HRK",
                            BaseNumber = 100,
                            FractionalUnit = "Lipa",
                            Name = "Croatian kuna",
                            Symbol = "kn"
                        },
                        new
                        {
                            CurrencyCode = "HTG",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Haitian gourde",
                            Symbol = "G"
                        },
                        new
                        {
                            CurrencyCode = "HUF",
                            BaseNumber = 100,
                            FractionalUnit = "Fillér",
                            Name = "Hungarian forint",
                            Symbol = "Ft"
                        },
                        new
                        {
                            CurrencyCode = "INR",
                            BaseNumber = 100,
                            FractionalUnit = "Paisa",
                            Name = "Indian rupee",
                            Symbol = "₹"
                        },
                        new
                        {
                            CurrencyCode = "IDR",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Indonesian rupiah",
                            Symbol = "Rp"
                        },
                        new
                        {
                            CurrencyCode = "IMP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Manx pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = "ILS",
                            BaseNumber = 100,
                            FractionalUnit = "Agora",
                            Name = "Israeli new shekel",
                            Symbol = "₪"
                        },
                        new
                        {
                            CurrencyCode = "ISK",
                            BaseNumber = 100,
                            FractionalUnit = "Eyrir",
                            Name = "Icelandic króna",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = "IRR",
                            BaseNumber = 100,
                            FractionalUnit = "Rial",
                            Name = "Iranian rial",
                            Symbol = "﷼"
                        },
                        new
                        {
                            CurrencyCode = "IQD",
                            BaseNumber = 1000,
                            FractionalUnit = "Fils",
                            Name = "Iraqi dinar",
                            Symbol = "ع.د"
                        },
                        new
                        {
                            CurrencyCode = "JEP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Jersey pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = "JMD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Jamaican dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "JPY",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Japanese yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            CurrencyCode = "JOD",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Jordanian dinar",
                            Symbol = "د.ا"
                        },
                        new
                        {
                            CurrencyCode = "KES",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Kenyan shilling",
                            Symbol = "Sh"
                        },
                        new
                        {
                            CurrencyCode = "KGS",
                            BaseNumber = 100,
                            FractionalUnit = "Tyiyn",
                            Name = "Kyrgyzstani som",
                            Symbol = "с"
                        },
                        new
                        {
                            CurrencyCode = "KHR",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Cambodian riel",
                            Symbol = "៛"
                        },
                        new
                        {
                            CurrencyCode = "KMF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Comorian franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyCode = "KID",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Kiribati dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "KPW",
                            BaseNumber = 100,
                            FractionalUnit = "Chon",
                            Name = "North Korean won",
                            Symbol = "₩"
                        },
                        new
                        {
                            CurrencyCode = "KRW",
                            BaseNumber = 100,
                            FractionalUnit = "Jeon",
                            Name = "South Korean won",
                            Symbol = "₩"
                        },
                        new
                        {
                            CurrencyCode = "KWD",
                            BaseNumber = 1000,
                            FractionalUnit = "Fils",
                            Name = "Kuwaiti dinar",
                            Symbol = "د.ك"
                        },
                        new
                        {
                            CurrencyCode = "KYD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Cayman Islands dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "KZT",
                            BaseNumber = 100,
                            FractionalUnit = "Tıyn",
                            Name = "Kazakhstani tenge",
                            Symbol = "₸"
                        },
                        new
                        {
                            CurrencyCode = "LAK",
                            BaseNumber = 100,
                            FractionalUnit = "Att",
                            Name = "Lao kip",
                            Symbol = "₭"
                        },
                        new
                        {
                            CurrencyCode = "LBP",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Lebanese pound",
                            Symbol = "ل.ل"
                        },
                        new
                        {
                            CurrencyCode = "LRD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Liberian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "LKR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Sri Lankan rupee",
                            Symbol = "ரூ"
                        },
                        new
                        {
                            CurrencyCode = "LSL",
                            BaseNumber = 100,
                            FractionalUnit = "Sente",
                            Name = "Lesotho loti",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyCode = "LYD",
                            BaseNumber = 1000,
                            FractionalUnit = "Dirham",
                            Name = "Libyan dinar",
                            Symbol = "ل.د"
                        },
                        new
                        {
                            CurrencyCode = "MGA",
                            BaseNumber = 5,
                            FractionalUnit = "Iraimbilanja",
                            Name = "Malagasy ariary",
                            Symbol = "Ar"
                        },
                        new
                        {
                            CurrencyCode = "MDL",
                            BaseNumber = 100,
                            FractionalUnit = "Ban",
                            Name = "Moldovan leu",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyCode = "MAD",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Moroccan dirham",
                            Symbol = "د.م."
                        },
                        new
                        {
                            CurrencyCode = "MOP",
                            BaseNumber = 100,
                            FractionalUnit = "Avo",
                            Name = "Macanese pataca",
                            Symbol = "P"
                        },
                        new
                        {
                            CurrencyCode = "MRU",
                            BaseNumber = 5,
                            FractionalUnit = "Khoums",
                            Name = "Mauritanian ouguiya",
                            Symbol = "UM"
                        },
                        new
                        {
                            CurrencyCode = "MNT",
                            BaseNumber = 100,
                            FractionalUnit = "Möngö",
                            Name = "Mongolian tögrög",
                            Symbol = "₮"
                        },
                        new
                        {
                            CurrencyCode = "MMK",
                            BaseNumber = 100,
                            FractionalUnit = "Pya",
                            Name = "Burmese kyat",
                            Symbol = "Ks"
                        },
                        new
                        {
                            CurrencyCode = "MKD",
                            BaseNumber = 100,
                            FractionalUnit = "Deni",
                            Name = "Macedonian denar",
                            Symbol = "ден"
                        },
                        new
                        {
                            CurrencyCode = "MWK",
                            BaseNumber = 100,
                            FractionalUnit = "Tambala",
                            Name = "Malawian kwacha",
                            Symbol = "MK"
                        },
                        new
                        {
                            CurrencyCode = "MYR",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Malaysian ringgit",
                            Symbol = "RM"
                        },
                        new
                        {
                            CurrencyCode = "MVR",
                            BaseNumber = 100,
                            FractionalUnit = "Laari",
                            Name = "Maldivian rufiyaa",
                            Symbol = ".ރ"
                        },
                        new
                        {
                            CurrencyCode = "MUR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Mauritian rupee",
                            Symbol = "₨"
                        },
                        new
                        {
                            CurrencyCode = "MXN",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Mexican peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "MZN",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Mozambican metical",
                            Symbol = "MT"
                        },
                        new
                        {
                            CurrencyCode = "NAD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Namibian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "NIO",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Nicaraguan córdoba",
                            Symbol = "C$"
                        },
                        new
                        {
                            CurrencyCode = "NGN",
                            BaseNumber = 100,
                            FractionalUnit = "Kobo",
                            Name = "Nigerian naira",
                            Symbol = "₦"
                        },
                        new
                        {
                            CurrencyCode = "NOK",
                            BaseNumber = 100,
                            FractionalUnit = "Øre",
                            Name = "Norwegian krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = "NPR",
                            BaseNumber = 100,
                            FractionalUnit = "Paisa",
                            Name = "Nepalese rupee",
                            Symbol = "रू"
                        },
                        new
                        {
                            CurrencyCode = "OMR",
                            BaseNumber = 1000,
                            FractionalUnit = "Baisa",
                            Name = "Omani rial",
                            Symbol = "ر.ع."
                        },
                        new
                        {
                            CurrencyCode = "PKR",
                            BaseNumber = 100,
                            FractionalUnit = "Paisa",
                            Name = "Pakistani rupee",
                            Symbol = "₨"
                        },
                        new
                        {
                            CurrencyCode = "PAB",
                            BaseNumber = 100,
                            FractionalUnit = "Centésimo",
                            Name = "Panamanian balboa",
                            Symbol = "B/."
                        },
                        new
                        {
                            CurrencyCode = "PGK",
                            BaseNumber = 100,
                            FractionalUnit = "Toea",
                            Name = "Papua New Guinean kina",
                            Symbol = "K"
                        },
                        new
                        {
                            CurrencyCode = "PEN",
                            BaseNumber = 100,
                            FractionalUnit = "Céntimo",
                            Name = "Peruvian sol",
                            Symbol = "S/."
                        },
                        new
                        {
                            CurrencyCode = "PHP",
                            BaseNumber = 100,
                            FractionalUnit = "Sentimo",
                            Name = "Philippine peso",
                            Symbol = "₱"
                        },
                        new
                        {
                            CurrencyCode = "PLN",
                            BaseNumber = 100,
                            FractionalUnit = "Grosz",
                            Name = "Polish złoty",
                            Symbol = "zł"
                        },
                        new
                        {
                            CurrencyCode = "NZD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "New Zealand dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "PND",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Pitcairn Islands dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "PYG",
                            BaseNumber = 100,
                            FractionalUnit = "Céntimo",
                            Name = "Paraguayan guaraní",
                            Symbol = "₲"
                        },
                        new
                        {
                            CurrencyCode = "QAR",
                            BaseNumber = 100,
                            FractionalUnit = "Dirham",
                            Name = "Qatari riyal",
                            Symbol = "ر.ق"
                        },
                        new
                        {
                            CurrencyCode = "RON",
                            BaseNumber = 100,
                            FractionalUnit = "Ban",
                            Name = "Romanian leu",
                            Symbol = "lei"
                        },
                        new
                        {
                            CurrencyCode = "RSD",
                            BaseNumber = 100,
                            FractionalUnit = "Para",
                            Name = "Serbian dinar",
                            Symbol = "дин"
                        },
                        new
                        {
                            CurrencyCode = "PRB",
                            BaseNumber = 100,
                            FractionalUnit = "Kopek",
                            Name = "Transnistrian ruble",
                            Symbol = "р."
                        },
                        new
                        {
                            CurrencyCode = "RUB",
                            BaseNumber = 100,
                            FractionalUnit = "Kopek",
                            Name = "Russian ruble",
                            Symbol = "₽"
                        },
                        new
                        {
                            CurrencyCode = "RWF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Rwandan franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyCode = "SAR",
                            BaseNumber = 100,
                            FractionalUnit = "Halala",
                            Name = "Saudi riyal",
                            Symbol = "﷼‎"
                        },
                        new
                        {
                            CurrencyCode = "SCR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Seychellois rupee",
                            Symbol = "₨"
                        },
                        new
                        {
                            CurrencyCode = "SBD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Solomon Islands dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "SHP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Saint Helena pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = "SGD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Singapore dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "SLL",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Sierra Leonean leone",
                            Symbol = "Le"
                        },
                        new
                        {
                            CurrencyCode = "SDG",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Sudanese pound",
                            Symbol = "ج.س."
                        },
                        new
                        {
                            CurrencyCode = "SEK",
                            BaseNumber = 100,
                            FractionalUnit = "Öre",
                            Name = "Swedish krona",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = "STN",
                            BaseNumber = 100,
                            FractionalUnit = "Cêntimo",
                            Name = "São Tomé and Príncipe dobra",
                            Symbol = "Db"
                        },
                        new
                        {
                            CurrencyCode = "SOS",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Somali shilling",
                            Symbol = "Sh"
                        },
                        new
                        {
                            CurrencyCode = "SLS",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Somaliland shilling",
                            Symbol = "Sl"
                        },
                        new
                        {
                            CurrencyCode = "SSP",
                            BaseNumber = 100,
                            FractionalUnit = "Piaster",
                            Name = "South Sudanese pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = "SRD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Surinamese dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "SYP",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Syrian pound",
                            Symbol = "ل.س"
                        },
                        new
                        {
                            CurrencyCode = "SZL",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Swazi lilangeni",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyCode = "TJS",
                            BaseNumber = 100,
                            FractionalUnit = "Diram",
                            Name = "Tajikistani somoni",
                            Symbol = "ЅМ"
                        },
                        new
                        {
                            CurrencyCode = "THB",
                            BaseNumber = 100,
                            FractionalUnit = "Satang",
                            Name = "Thai baht",
                            Symbol = "฿"
                        },
                        new
                        {
                            CurrencyCode = "TOP",
                            BaseNumber = 100,
                            FractionalUnit = "Seniti",
                            Name = "Tongan paʻanga",
                            Symbol = "T$"
                        },
                        new
                        {
                            CurrencyCode = "TND",
                            BaseNumber = 1000,
                            FractionalUnit = "Millime",
                            Name = "Tunisian dinar",
                            Symbol = "د.ت"
                        },
                        new
                        {
                            CurrencyCode = "TMT",
                            BaseNumber = 100,
                            FractionalUnit = "Tennesi",
                            Name = "Turkmenistan manat",
                            Symbol = "m"
                        },
                        new
                        {
                            CurrencyCode = "TRY",
                            BaseNumber = 100,
                            FractionalUnit = "Kuruş",
                            Name = "Turkish lira",
                            Symbol = "₺"
                        },
                        new
                        {
                            CurrencyCode = "TWD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "New Taiwan dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "TZS",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Tanzanian shilling",
                            Symbol = "Sh"
                        },
                        new
                        {
                            CurrencyCode = "TTD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Trinidad and Tobago dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "TVD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Tuvaluan dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "UAH",
                            BaseNumber = 100,
                            FractionalUnit = "Kopiyka",
                            Name = "Ukrainian hryvnia",
                            Symbol = "₴"
                        },
                        new
                        {
                            CurrencyCode = "USD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "United States dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "UGX",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Ugandan shilling",
                            Symbol = "Sh"
                        },
                        new
                        {
                            CurrencyCode = "UYU",
                            BaseNumber = 100,
                            FractionalUnit = "Centésimo",
                            Name = "Uruguayan peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "UZS",
                            BaseNumber = 100,
                            FractionalUnit = "Tiyin",
                            Name = "Uzbekistani soʻm",
                            Symbol = "сўм"
                        },
                        new
                        {
                            CurrencyCode = "VES",
                            BaseNumber = 100,
                            FractionalUnit = "Céntimo",
                            Name = "Venezuelan bolívar soberano",
                            Symbol = "Bs."
                        },
                        new
                        {
                            CurrencyCode = "VND",
                            BaseNumber = 10,
                            FractionalUnit = "Hào",
                            Name = "Vietnamese đồng",
                            Symbol = "₫"
                        },
                        new
                        {
                            CurrencyCode = "XCD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Eastern Caribbean dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = "XOF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "West African CFA franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyCode = "XAF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Central African CFA franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyCode = "XPF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "CFP franc",
                            Symbol = "₣"
                        },
                        new
                        {
                            CurrencyCode = "WST",
                            BaseNumber = 100,
                            FractionalUnit = "Sene",
                            Name = "Samoan tālā",
                            Symbol = "T"
                        },
                        new
                        {
                            CurrencyCode = "VUV",
                            BaseNumber = 100,
                            FractionalUnit = "",
                            Name = "Vanuatu vatu",
                            Symbol = "Vt"
                        },
                        new
                        {
                            CurrencyCode = "ZAR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "South African rand",
                            Symbol = "R"
                        },
                        new
                        {
                            CurrencyCode = "YER",
                            BaseNumber = 100,
                            FractionalUnit = "Fils",
                            Name = "Yemeni rial",
                            Symbol = "ر.ي"
                        },
                        new
                        {
                            CurrencyCode = "ZMW",
                            BaseNumber = 100,
                            FractionalUnit = "Ngwee",
                            Name = "Zambian kwacha",
                            Symbol = "ZK"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Country", b =>
                {
                    b.HasOne("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Continent", "Continent")
                        .WithMany()
                        .HasForeignKey("ContinentCode");

                    b.HasOne("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode");
                });
#pragma warning restore 612, 618
        }
    }
}
