// <auto-generated />
using MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Migrations
{
    [DbContext(typeof(MetaDataDatabaseContext))]
    [Migration("20200816160603_Adding Few Countries")]
    partial class AddingFewCountries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Continent", b =>
                {
                    b.Property<HierarchyId>("ContinentId")
                        .HasColumnType("hierarchyid");

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentId");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/"),
                            ContinentName = "Africa"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/2/"),
                            ContinentName = "Antarctica"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/"),
                            ContinentName = "Asia"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/"),
                            ContinentName = "Europe"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/"),
                            ContinentName = "North America"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/"),
                            ContinentName = "South America"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/"),
                            ContinentName = "Australia"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Country", b =>
                {
                    b.Property<HierarchyId>("CountryId")
                        .HasColumnType("hierarchyid");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/1/"),
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/2/"),
                            CountryName = "Armenia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/3/"),
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/4/"),
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/5/"),
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/6/"),
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/7/"),
                            CountryName = "Brunei"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/8/"),
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/9/"),
                            CountryName = "China"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/10/"),
                            CountryName = "East Timor"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/11/"),
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/12/"),
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/13/"),
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/14/"),
                            CountryName = "Iran"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/15/"),
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/16/"),
                            CountryName = "Israel"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/17/"),
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/18/"),
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/19/"),
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/20/"),
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/21/"),
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/22/"),
                            CountryName = "Laos"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/23/"),
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/24/"),
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/25/"),
                            CountryName = "Maldives"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/26/"),
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/27/"),
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/28/"),
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/29/"),
                            CountryName = "North Korea"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/30/"),
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/31/"),
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/32/"),
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/33/"),
                            CountryName = "Palestine"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/34/"),
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/35/"),
                            CountryName = "Russia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/36/"),
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/37/"),
                            CountryName = "Singapore"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/38/"),
                            CountryName = "South Korea"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/39/"),
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/40/"),
                            CountryName = "Syria"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/41/"),
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/42/"),
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/43/"),
                            CountryName = "Turkey"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/44/"),
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/45/"),
                            CountryName = "Taiwan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/46/"),
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/47/"),
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/48/"),
                            CountryName = "Vietnam"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/49/"),
                            CountryName = "Yemen"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Planet", b =>
                {
                    b.Property<HierarchyId>("PlanetId")
                        .HasColumnType("hierarchyid");

                    b.Property<string>("PlanetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanetId");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            PlanetId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/"),
                            PlanetName = "Earth"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
