// <auto-generated />
using System;
using MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Migrations
{
    [DbContext(typeof(MetaDataDatabaseContext))]
    [Migration("20200906133228_Removed Currency Seed Data")]
    partial class RemovedCurrencySeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Continent", b =>
                {
                    b.Property<HierarchyId>("ContinentId")
                        .HasColumnType("hierarchyid");

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentId");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/"),
                            ContinentName = "Africa"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/2/"),
                            ContinentName = "Antarctica"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/"),
                            ContinentName = "Asia"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/"),
                            ContinentName = "Europe"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/"),
                            ContinentName = "North America"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/"),
                            ContinentName = "South America"
                        },
                        new
                        {
                            ContinentId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/"),
                            ContinentName = "Australia"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Country", b =>
                {
                    b.Property<HierarchyId>("CountryId")
                        .HasColumnType("hierarchyid");

                    b.Property<string>("CallingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<HierarchyId>("CurrencyId")
                        .HasColumnType("hierarchyid");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISOCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrthographicMap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/1/"),
                            CountryName = "Algeria"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/2/"),
                            CountryName = "Angola"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/3/"),
                            CountryName = "Benin"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/4/"),
                            CountryName = "Botswana"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/5/"),
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/6/"),
                            CountryName = "Burundi"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/7/"),
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/8/"),
                            CountryName = "Cape Verde"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/9/"),
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/10/"),
                            CountryName = "Chad"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/11/"),
                            CountryName = "Comoros"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/12/"),
                            CountryName = "Republic of the Congo"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/13/"),
                            CountryName = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/14/"),
                            CountryName = "Ivory Coast"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/15/"),
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/16/"),
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/17/"),
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/18/"),
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/19/"),
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/20/"),
                            CountryName = "Gabon"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/21/"),
                            CountryName = "The Gambia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/22/"),
                            CountryName = "Ghana"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/23/"),
                            CountryName = "Guinea"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/24/"),
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/25/"),
                            CountryName = "Kenya"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/26/"),
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/27/"),
                            CountryName = "Liberia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/28/"),
                            CountryName = "Libya"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/29/"),
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/30/"),
                            CountryName = "Malawi"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/31/"),
                            CountryName = "Mali"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/32/"),
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/33/"),
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/34/"),
                            CountryName = "Morocco"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/35/"),
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/36/"),
                            CountryName = "Namibia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/37/"),
                            CountryName = "Niger"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/38/"),
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/39/"),
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/40/"),
                            CountryName = "São Tomé and Príncipe"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/41/"),
                            CountryName = "Senegal"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/42/"),
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/43/"),
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/44/"),
                            CountryName = "Somalia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/45/"),
                            CountryName = "South Africa"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/46/"),
                            CountryName = "South Sudan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/47/"),
                            CountryName = "Sudan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/48/"),
                            CountryName = "Swaziland"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/49/"),
                            CountryName = "Tanzania"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/50/"),
                            CountryName = "Togo"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/51/"),
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/52/"),
                            CountryName = "Uganda"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/53/"),
                            CountryName = "Western Sahara"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/54/"),
                            CountryName = "Zambia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/55/"),
                            CountryName = "Zimbabwe"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/1/"),
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/2/"),
                            CountryName = "Armenia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/3/"),
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/4/"),
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/5/"),
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/6/"),
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/7/"),
                            CountryName = "Brunei"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/8/"),
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/9/"),
                            CountryName = "China"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/10/"),
                            CountryName = "East Timor"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/11/"),
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/12/"),
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/13/"),
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/14/"),
                            CountryName = "Iran"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/15/"),
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/16/"),
                            CountryName = "Israel"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/17/"),
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/18/"),
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/19/"),
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/20/"),
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/21/"),
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/22/"),
                            CountryName = "Laos"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/23/"),
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/24/"),
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/25/"),
                            CountryName = "Maldives"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/26/"),
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/27/"),
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/28/"),
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/29/"),
                            CountryName = "North Korea"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/30/"),
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/31/"),
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/32/"),
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/33/"),
                            CountryName = "Palestine"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/34/"),
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/35/"),
                            CountryName = "Russia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/36/"),
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/37/"),
                            CountryName = "Singapore"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/38/"),
                            CountryName = "South Korea"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/39/"),
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/40/"),
                            CountryName = "Syria"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/41/"),
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/42/"),
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/43/"),
                            CountryName = "Turkey"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/44/"),
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/45/"),
                            CountryName = "Taiwan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/46/"),
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/47/"),
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/48/"),
                            CountryName = "Vietnam"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/3/49/"),
                            CountryName = "Yemen"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/1/"),
                            CountryName = "Albania"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/2/"),
                            CountryName = "Andorra"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/3/"),
                            CountryName = "Austria"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/4/"),
                            CountryName = "Belarus"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/5/"),
                            CountryName = "Belgium"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/6/"),
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/7/"),
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/8/"),
                            CountryName = "Croatia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/9/"),
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/10/"),
                            CountryName = "Czech Republic"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/11/"),
                            CountryName = "Denmark"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/12/"),
                            CountryName = "Estonia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/13/"),
                            CountryName = "Finland"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/14/"),
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/15/"),
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/16/"),
                            CountryName = "Greece"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/17/"),
                            CountryName = "Hungary"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/18/"),
                            CountryName = "Iceland"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/19/"),
                            CountryName = "Republic of Ireland"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/20/"),
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/21/"),
                            CountryName = "Kosovo"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/22/"),
                            CountryName = "Latvia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/23/"),
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/24/"),
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/25/"),
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/26/"),
                            CountryName = "North Macedonia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/27/"),
                            CountryName = "Malta"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/28/"),
                            CountryName = "Moldova"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/29/"),
                            CountryName = "Monaco"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/30/"),
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/31/"),
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/32/"),
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/33/"),
                            CountryName = "Poland"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/34/"),
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/35/"),
                            CountryName = "Romania"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/36/"),
                            CountryName = "Moscow"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/37/"),
                            CountryName = "San Marino"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/38/"),
                            CountryName = "Serbia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/39/"),
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/40/"),
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/41/"),
                            CountryName = "Spain"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/42/"),
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/43/"),
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/44/"),
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/45/"),
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/4/46/"),
                            CountryName = "Vatican City"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/1/"),
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/2/"),
                            CountryName = "Anguilla"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/3/"),
                            CountryName = "Aruba"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/4/"),
                            CountryName = "The Bahamas"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/5/"),
                            CountryName = "Barbados"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/6/"),
                            CountryName = "Belize"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/7/"),
                            CountryName = "Bermuda"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/8/"),
                            CountryName = "Bonaire"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/9/"),
                            CountryName = "British Virgin Islands"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/10/"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/11/"),
                            CountryName = "Cayman Islands"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/12/"),
                            CountryName = "Clipperton Island"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/13/"),
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/14/"),
                            CountryName = "Cuba"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/15/"),
                            CountryName = "Curaçao"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/16/"),
                            CountryName = "Dominica"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/17/"),
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/18/"),
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/19/"),
                            CountryName = "Greenland"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/20/"),
                            CountryName = "Grenada"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/21/"),
                            CountryName = "Guadeloupe"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/22/"),
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/23/"),
                            CountryName = "Haiti"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/24/"),
                            CountryName = "Honduras"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/25/"),
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/26/"),
                            CountryName = "Martinique"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/27/"),
                            CountryName = "Mexico"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/28/"),
                            CountryName = "Montserrat"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/29/"),
                            CountryName = "Navassa Island"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/30/"),
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/31/"),
                            CountryName = "Panama"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/32/"),
                            CountryName = "Puerto Rico"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/33/"),
                            CountryName = "Saba"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/34/"),
                            CountryName = "Saint Barthelemy"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/35/"),
                            CountryName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/36/"),
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/37/"),
                            CountryName = "Saint Martin"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/38/"),
                            CountryName = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/39/"),
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/40/"),
                            CountryName = "Sint Eustatius"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/41/"),
                            CountryName = "Sint Maarten"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/42/"),
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/43/"),
                            CountryName = "Turks and Caicos"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/44/"),
                            CountryName = "United States of America"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/5/45/"),
                            CountryName = "US Virgin Islands"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/1/"),
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/2/"),
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/3/"),
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/4/"),
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/5/"),
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/6/"),
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/7/"),
                            CountryName = "Falkland Islands"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/8/"),
                            CountryName = "French Guiana"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/9/"),
                            CountryName = "Guyana"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/10/"),
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/11/"),
                            CountryName = "Peru"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/12/"),
                            CountryName = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/13/"),
                            CountryName = "Suriname"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/14/"),
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/6/15/"),
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/1/"),
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/2/"),
                            CountryName = "Federated States of Micronesia"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/3/"),
                            CountryName = "Fiji"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/4/"),
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/5/"),
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/6/"),
                            CountryName = "Nauru"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/7/"),
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/8/"),
                            CountryName = "Palau"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/9/"),
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/10/"),
                            CountryName = "Samoa"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/11/"),
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/12/"),
                            CountryName = "Tonga"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/13/"),
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            CountryId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/7/14/"),
                            CountryName = "Vanuatu"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Currency", b =>
                {
                    b.Property<HierarchyId>("CurrencyId")
                        .HasColumnType("hierarchyid");

                    b.Property<int?>("BaseNumber")
                        .HasColumnType("int");

                    b.Property<string>("FractionalUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISOCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Planet", b =>
                {
                    b.Property<HierarchyId>("PlanetId")
                        .HasColumnType("hierarchyid");

                    b.Property<string>("PlanetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanetId");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            PlanetId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/"),
                            PlanetName = "Earth"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Country", b =>
                {
                    b.HasOne("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");
                });
#pragma warning restore 612, 618
        }
    }
}
