// <auto-generated />
using System;
using MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Migrations
{
    [DbContext(typeof(MetaDataDatabaseContext))]
    [Migration("20200910163754_Changed Contienet Primary Key")]
    partial class ChangedContienetPrimaryKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Continent", b =>
                {
                    b.Property<string>("ContinentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentCode");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Country", b =>
                {
                    b.Property<string>("CountryISOCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CallingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyISOCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISOCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrthographicMap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryISOCode");

                    b.HasIndex("CurrencyISOCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Currency", b =>
                {
                    b.Property<string>("CurrencyISOCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BaseNumber")
                        .HasColumnType("int");

                    b.Property<string>("FractionalUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyISOCode");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            CurrencyISOCode = "AED",
                            BaseNumber = 100,
                            FractionalUnit = "Fils",
                            Name = "United Arab Emirates dirham",
                            Symbol = "د.إ"
                        },
                        new
                        {
                            CurrencyISOCode = "AFN",
                            BaseNumber = 100,
                            FractionalUnit = "Pul",
                            Name = "Afghan afghani",
                            Symbol = "؋"
                        },
                        new
                        {
                            CurrencyISOCode = "ALL",
                            BaseNumber = 100,
                            FractionalUnit = "Qindarkë",
                            Name = "Albanian lek",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyISOCode = "AMD",
                            BaseNumber = 100,
                            FractionalUnit = "Luma",
                            Name = "Armenian dram",
                            Symbol = "֏"
                        },
                        new
                        {
                            CurrencyISOCode = "ANG",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Netherlands Antillean guilder",
                            Symbol = "ƒ"
                        },
                        new
                        {
                            CurrencyISOCode = "AOA",
                            BaseNumber = 100,
                            FractionalUnit = "Cêntimo",
                            Name = "Angolan kwanza",
                            Symbol = "Kz"
                        },
                        new
                        {
                            CurrencyISOCode = "ARS",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Argentine peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "AUD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Australian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "AWG",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Aruban florin",
                            Symbol = "ƒ"
                        },
                        new
                        {
                            CurrencyISOCode = "AZN",
                            BaseNumber = 100,
                            FractionalUnit = "Qəpik",
                            Name = "Azerbaijani manat",
                            Symbol = "₼"
                        },
                        new
                        {
                            CurrencyISOCode = "BAM",
                            BaseNumber = 100,
                            FractionalUnit = "Fening",
                            Name = "Bosnia and Herzegovina convertible mark",
                            Symbol = "KM"
                        },
                        new
                        {
                            CurrencyISOCode = "BBD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Barbadian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "BDT",
                            BaseNumber = 100,
                            FractionalUnit = "Poisha",
                            Name = "Bangladeshi taka",
                            Symbol = "৳"
                        },
                        new
                        {
                            CurrencyISOCode = "BGN",
                            BaseNumber = 100,
                            FractionalUnit = "Stotinka",
                            Name = "Bulgarian lev",
                            Symbol = "лв."
                        },
                        new
                        {
                            CurrencyISOCode = "BHD",
                            BaseNumber = 1000,
                            FractionalUnit = "Fils",
                            Name = "Bahraini dinar",
                            Symbol = ".د.ب"
                        },
                        new
                        {
                            CurrencyISOCode = "BIF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Burundian franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyISOCode = "BMD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Bermudian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "BND",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Brunei dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "BOB",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Bolivian boliviano",
                            Symbol = "Bs."
                        },
                        new
                        {
                            CurrencyISOCode = "BRL",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Brazilian real",
                            Symbol = "R$"
                        },
                        new
                        {
                            CurrencyISOCode = "BSD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Bahamian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "BTN",
                            BaseNumber = 100,
                            FractionalUnit = "Chetrum",
                            Name = "Bhutanese ngultrum",
                            Symbol = "Nu."
                        },
                        new
                        {
                            CurrencyISOCode = "BWP",
                            BaseNumber = 100,
                            FractionalUnit = "Thebe",
                            Name = "Botswana pula",
                            Symbol = "P"
                        },
                        new
                        {
                            CurrencyISOCode = "BYN",
                            BaseNumber = 100,
                            FractionalUnit = "Kapyeyka",
                            Name = "Belarusian ruble",
                            Symbol = "Br"
                        },
                        new
                        {
                            CurrencyISOCode = "BZD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Belize dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "CAD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Canadian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "CDF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Congolese franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyISOCode = "CHF",
                            BaseNumber = 100,
                            FractionalUnit = "Rappen",
                            Name = "Swiss franc",
                            Symbol = "Fr."
                        },
                        new
                        {
                            CurrencyISOCode = "CLP",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Chilean peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "CNY",
                            BaseNumber = 10,
                            FractionalUnit = "Jiao",
                            Name = "Chinese yuan",
                            Symbol = "¥"
                        },
                        new
                        {
                            CurrencyISOCode = "CKD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Cook Islands dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "COP",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Colombian peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "CRC",
                            BaseNumber = 100,
                            FractionalUnit = "Céntimo",
                            Name = "Costa Rican colón",
                            Symbol = "₡"
                        },
                        new
                        {
                            CurrencyISOCode = "CUC",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Cuban convertible peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "CVE",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Cape Verdean escudo",
                            Symbol = "Esc"
                        },
                        new
                        {
                            CurrencyISOCode = "CUP",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Cuban peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "CZK",
                            BaseNumber = 100,
                            FractionalUnit = "Haléř",
                            Name = "Czech koruna",
                            Symbol = "Kč"
                        },
                        new
                        {
                            CurrencyISOCode = "DJF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Djiboutian franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyISOCode = "DZD",
                            BaseNumber = 100,
                            FractionalUnit = "Santeem",
                            Name = "Algerian dinar",
                            Symbol = "د.ج"
                        },
                        new
                        {
                            CurrencyISOCode = "DKK",
                            BaseNumber = 100,
                            FractionalUnit = "Øre",
                            Name = "Danish krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyISOCode = "DOP",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Dominican peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "EGP",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Egyptian pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyISOCode = "ERN",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Eritrean nakfa",
                            Symbol = "Nfk"
                        },
                        new
                        {
                            CurrencyISOCode = "ETB",
                            BaseNumber = 100,
                            FractionalUnit = "Santim",
                            Name = "Ethiopian birr",
                            Symbol = "Br"
                        },
                        new
                        {
                            CurrencyISOCode = "EUR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            CurrencyISOCode = "FKP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Falkland Islands pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyISOCode = "FOK",
                            BaseNumber = 100,
                            FractionalUnit = "Oyra",
                            Name = "Faroese króna",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyISOCode = "FJD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Fijian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "GBP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "British pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyISOCode = "GGP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Guernsey pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyISOCode = "GEL",
                            BaseNumber = 100,
                            FractionalUnit = "Tetri",
                            Name = "Georgian lari",
                            Symbol = "₾"
                        },
                        new
                        {
                            CurrencyISOCode = "GMD",
                            BaseNumber = 100,
                            FractionalUnit = "Butut",
                            Name = "Gambian dalasi",
                            Symbol = "D"
                        },
                        new
                        {
                            CurrencyISOCode = "GHS",
                            BaseNumber = 100,
                            FractionalUnit = "Pesewa",
                            Name = "Ghanaian cedi",
                            Symbol = "₵"
                        },
                        new
                        {
                            CurrencyISOCode = "GIP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Gibraltar pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyISOCode = "GNF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Guinean franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyISOCode = "GTQ",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Guatemalan quetzal",
                            Symbol = "Q"
                        },
                        new
                        {
                            CurrencyISOCode = "GYD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Guyanese dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "HNL",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Honduran lempira",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyISOCode = "HKD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Hong Kong dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "HRK",
                            BaseNumber = 100,
                            FractionalUnit = "Lipa",
                            Name = "Croatian kuna",
                            Symbol = "kn"
                        },
                        new
                        {
                            CurrencyISOCode = "HTG",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Haitian gourde",
                            Symbol = "G"
                        },
                        new
                        {
                            CurrencyISOCode = "HUF",
                            BaseNumber = 100,
                            FractionalUnit = "Fillér",
                            Name = "Hungarian forint",
                            Symbol = "Ft"
                        },
                        new
                        {
                            CurrencyISOCode = "INR",
                            BaseNumber = 100,
                            FractionalUnit = "Paisa",
                            Name = "Indian rupee",
                            Symbol = "₹"
                        },
                        new
                        {
                            CurrencyISOCode = "IDR",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Indonesian rupiah",
                            Symbol = "Rp"
                        },
                        new
                        {
                            CurrencyISOCode = "IMP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Manx pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyISOCode = "ILS",
                            BaseNumber = 100,
                            FractionalUnit = "Agora",
                            Name = "Israeli new shekel",
                            Symbol = "₪"
                        },
                        new
                        {
                            CurrencyISOCode = "ISK",
                            BaseNumber = 100,
                            FractionalUnit = "Eyrir",
                            Name = "Icelandic króna",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyISOCode = "IRR",
                            BaseNumber = 100,
                            FractionalUnit = "Rial",
                            Name = "Iranian rial",
                            Symbol = "﷼"
                        },
                        new
                        {
                            CurrencyISOCode = "IQD",
                            BaseNumber = 1000,
                            FractionalUnit = "Fils",
                            Name = "Iraqi dinar",
                            Symbol = "ع.د"
                        },
                        new
                        {
                            CurrencyISOCode = "JEP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Jersey pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyISOCode = "JMD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Jamaican dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "JPY",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Japanese yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            CurrencyISOCode = "JOD",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Jordanian dinar",
                            Symbol = "د.ا"
                        },
                        new
                        {
                            CurrencyISOCode = "KES",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Kenyan shilling",
                            Symbol = "Sh"
                        },
                        new
                        {
                            CurrencyISOCode = "KGS",
                            BaseNumber = 100,
                            FractionalUnit = "Tyiyn",
                            Name = "Kyrgyzstani som",
                            Symbol = "с"
                        },
                        new
                        {
                            CurrencyISOCode = "KHR",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Cambodian riel",
                            Symbol = "៛"
                        },
                        new
                        {
                            CurrencyISOCode = "KMF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Comorian franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyISOCode = "KID",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Kiribati dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "KPW",
                            BaseNumber = 100,
                            FractionalUnit = "Chon",
                            Name = "North Korean won",
                            Symbol = "₩"
                        },
                        new
                        {
                            CurrencyISOCode = "KRW",
                            BaseNumber = 100,
                            FractionalUnit = "Jeon",
                            Name = "South Korean won",
                            Symbol = "₩"
                        },
                        new
                        {
                            CurrencyISOCode = "KWD",
                            BaseNumber = 1000,
                            FractionalUnit = "Fils",
                            Name = "Kuwaiti dinar",
                            Symbol = "د.ك"
                        },
                        new
                        {
                            CurrencyISOCode = "KYD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Cayman Islands dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "KZT",
                            BaseNumber = 100,
                            FractionalUnit = "Tıyn",
                            Name = "Kazakhstani tenge",
                            Symbol = "₸"
                        },
                        new
                        {
                            CurrencyISOCode = "LAK",
                            BaseNumber = 100,
                            FractionalUnit = "Att",
                            Name = "Lao kip",
                            Symbol = "₭"
                        },
                        new
                        {
                            CurrencyISOCode = "LBP",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Lebanese pound",
                            Symbol = "ل.ل"
                        },
                        new
                        {
                            CurrencyISOCode = "LRD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Liberian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "LKR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Sri Lankan rupee",
                            Symbol = "ரூ"
                        },
                        new
                        {
                            CurrencyISOCode = "LSL",
                            BaseNumber = 100,
                            FractionalUnit = "Sente",
                            Name = "Lesotho loti",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyISOCode = "LYD",
                            BaseNumber = 1000,
                            FractionalUnit = "Dirham",
                            Name = "Libyan dinar",
                            Symbol = "ل.د"
                        },
                        new
                        {
                            CurrencyISOCode = "MGA",
                            BaseNumber = 5,
                            FractionalUnit = "Iraimbilanja",
                            Name = "Malagasy ariary",
                            Symbol = "Ar"
                        },
                        new
                        {
                            CurrencyISOCode = "MDL",
                            BaseNumber = 100,
                            FractionalUnit = "Ban",
                            Name = "Moldovan leu",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyISOCode = "MAD",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Moroccan dirham",
                            Symbol = "د.م."
                        },
                        new
                        {
                            CurrencyISOCode = "MOP",
                            BaseNumber = 100,
                            FractionalUnit = "Avo",
                            Name = "Macanese pataca",
                            Symbol = "P"
                        },
                        new
                        {
                            CurrencyISOCode = "MRU",
                            BaseNumber = 5,
                            FractionalUnit = "Khoums",
                            Name = "Mauritanian ouguiya",
                            Symbol = "UM"
                        },
                        new
                        {
                            CurrencyISOCode = "MNT",
                            BaseNumber = 100,
                            FractionalUnit = "Möngö",
                            Name = "Mongolian tögrög",
                            Symbol = "₮"
                        },
                        new
                        {
                            CurrencyISOCode = "MMK",
                            BaseNumber = 100,
                            FractionalUnit = "Pya",
                            Name = "Burmese kyat",
                            Symbol = "Ks"
                        },
                        new
                        {
                            CurrencyISOCode = "MKD",
                            BaseNumber = 100,
                            FractionalUnit = "Deni",
                            Name = "Macedonian denar",
                            Symbol = "ден"
                        },
                        new
                        {
                            CurrencyISOCode = "MWK",
                            BaseNumber = 100,
                            FractionalUnit = "Tambala",
                            Name = "Malawian kwacha",
                            Symbol = "MK"
                        },
                        new
                        {
                            CurrencyISOCode = "MYR",
                            BaseNumber = 100,
                            FractionalUnit = "Sen",
                            Name = "Malaysian ringgit",
                            Symbol = "RM"
                        },
                        new
                        {
                            CurrencyISOCode = "MVR",
                            BaseNumber = 100,
                            FractionalUnit = "Laari",
                            Name = "Maldivian rufiyaa",
                            Symbol = ".ރ"
                        },
                        new
                        {
                            CurrencyISOCode = "MUR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Mauritian rupee",
                            Symbol = "₨"
                        },
                        new
                        {
                            CurrencyISOCode = "MXN",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Mexican peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "MZN",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Mozambican metical",
                            Symbol = "MT"
                        },
                        new
                        {
                            CurrencyISOCode = "NAD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Namibian dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "NIO",
                            BaseNumber = 100,
                            FractionalUnit = "Centavo",
                            Name = "Nicaraguan córdoba",
                            Symbol = "C$"
                        },
                        new
                        {
                            CurrencyISOCode = "NGN",
                            BaseNumber = 100,
                            FractionalUnit = "Kobo",
                            Name = "Nigerian naira",
                            Symbol = "₦"
                        },
                        new
                        {
                            CurrencyISOCode = "NOK",
                            BaseNumber = 100,
                            FractionalUnit = "Øre",
                            Name = "Norwegian krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyISOCode = "NPR",
                            BaseNumber = 100,
                            FractionalUnit = "Paisa",
                            Name = "Nepalese rupee",
                            Symbol = "रू"
                        },
                        new
                        {
                            CurrencyISOCode = "OMR",
                            BaseNumber = 1000,
                            FractionalUnit = "Baisa",
                            Name = "Omani rial",
                            Symbol = "ر.ع."
                        },
                        new
                        {
                            CurrencyISOCode = "PKR",
                            BaseNumber = 100,
                            FractionalUnit = "Paisa",
                            Name = "Pakistani rupee",
                            Symbol = "₨"
                        },
                        new
                        {
                            CurrencyISOCode = "PAB",
                            BaseNumber = 100,
                            FractionalUnit = "Centésimo",
                            Name = "Panamanian balboa",
                            Symbol = "B/."
                        },
                        new
                        {
                            CurrencyISOCode = "PGK",
                            BaseNumber = 100,
                            FractionalUnit = "Toea",
                            Name = "Papua New Guinean kina",
                            Symbol = "K"
                        },
                        new
                        {
                            CurrencyISOCode = "PEN",
                            BaseNumber = 100,
                            FractionalUnit = "Céntimo",
                            Name = "Peruvian sol",
                            Symbol = "S/."
                        },
                        new
                        {
                            CurrencyISOCode = "PHP",
                            BaseNumber = 100,
                            FractionalUnit = "Sentimo",
                            Name = "Philippine peso",
                            Symbol = "₱"
                        },
                        new
                        {
                            CurrencyISOCode = "PLN",
                            BaseNumber = 100,
                            FractionalUnit = "Grosz",
                            Name = "Polish złoty",
                            Symbol = "zł"
                        },
                        new
                        {
                            CurrencyISOCode = "NZD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "New Zealand dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "PND",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Pitcairn Islands dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "PYG",
                            BaseNumber = 100,
                            FractionalUnit = "Céntimo",
                            Name = "Paraguayan guaraní",
                            Symbol = "₲"
                        },
                        new
                        {
                            CurrencyISOCode = "QAR",
                            BaseNumber = 100,
                            FractionalUnit = "Dirham",
                            Name = "Qatari riyal",
                            Symbol = "ر.ق"
                        },
                        new
                        {
                            CurrencyISOCode = "RON",
                            BaseNumber = 100,
                            FractionalUnit = "Ban",
                            Name = "Romanian leu",
                            Symbol = "lei"
                        },
                        new
                        {
                            CurrencyISOCode = "RSD",
                            BaseNumber = 100,
                            FractionalUnit = "Para",
                            Name = "Serbian dinar",
                            Symbol = "дин"
                        },
                        new
                        {
                            CurrencyISOCode = "PRB",
                            BaseNumber = 100,
                            FractionalUnit = "Kopek",
                            Name = "Transnistrian ruble",
                            Symbol = "р."
                        },
                        new
                        {
                            CurrencyISOCode = "RUB",
                            BaseNumber = 100,
                            FractionalUnit = "Kopek",
                            Name = "Russian ruble",
                            Symbol = "₽"
                        },
                        new
                        {
                            CurrencyISOCode = "RWF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Rwandan franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyISOCode = "SAR",
                            BaseNumber = 100,
                            FractionalUnit = "Halala",
                            Name = "Saudi riyal",
                            Symbol = "﷼‎"
                        },
                        new
                        {
                            CurrencyISOCode = "SCR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Seychellois rupee",
                            Symbol = "₨"
                        },
                        new
                        {
                            CurrencyISOCode = "SBD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Solomon Islands dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "SHP",
                            BaseNumber = 100,
                            FractionalUnit = "Penny",
                            Name = "Saint Helena pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyISOCode = "SGD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Singapore dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "SLL",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Sierra Leonean leone",
                            Symbol = "Le"
                        },
                        new
                        {
                            CurrencyISOCode = "SDG",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Sudanese pound",
                            Symbol = "ج.س."
                        },
                        new
                        {
                            CurrencyISOCode = "SEK",
                            BaseNumber = 100,
                            FractionalUnit = "Öre",
                            Name = "Swedish krona",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyISOCode = "STN",
                            BaseNumber = 100,
                            FractionalUnit = "Cêntimo",
                            Name = "São Tomé and Príncipe dobra",
                            Symbol = "Db"
                        },
                        new
                        {
                            CurrencyISOCode = "SOS",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Somali shilling",
                            Symbol = "Sh"
                        },
                        new
                        {
                            CurrencyISOCode = "SLS",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Somaliland shilling",
                            Symbol = "Sl"
                        },
                        new
                        {
                            CurrencyISOCode = "SSP",
                            BaseNumber = 100,
                            FractionalUnit = "Piaster",
                            Name = "South Sudanese pound",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyISOCode = "SRD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Surinamese dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "SYP",
                            BaseNumber = 100,
                            FractionalUnit = "Piastre",
                            Name = "Syrian pound",
                            Symbol = "ل.س"
                        },
                        new
                        {
                            CurrencyISOCode = "SZL",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Swazi lilangeni",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyISOCode = "TJS",
                            BaseNumber = 100,
                            FractionalUnit = "Diram",
                            Name = "Tajikistani somoni",
                            Symbol = "ЅМ"
                        },
                        new
                        {
                            CurrencyISOCode = "THB",
                            BaseNumber = 100,
                            FractionalUnit = "Satang",
                            Name = "Thai baht",
                            Symbol = "฿"
                        },
                        new
                        {
                            CurrencyISOCode = "TOP",
                            BaseNumber = 100,
                            FractionalUnit = "Seniti",
                            Name = "Tongan paʻanga",
                            Symbol = "T$"
                        },
                        new
                        {
                            CurrencyISOCode = "TND",
                            BaseNumber = 1000,
                            FractionalUnit = "Millime",
                            Name = "Tunisian dinar",
                            Symbol = "د.ت"
                        },
                        new
                        {
                            CurrencyISOCode = "TMT",
                            BaseNumber = 100,
                            FractionalUnit = "Tennesi",
                            Name = "Turkmenistan manat",
                            Symbol = "m"
                        },
                        new
                        {
                            CurrencyISOCode = "TRY",
                            BaseNumber = 100,
                            FractionalUnit = "Kuruş",
                            Name = "Turkish lira",
                            Symbol = "₺"
                        },
                        new
                        {
                            CurrencyISOCode = "TWD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "New Taiwan dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "TZS",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Tanzanian shilling",
                            Symbol = "Sh"
                        },
                        new
                        {
                            CurrencyISOCode = "TTD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Trinidad and Tobago dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "TVD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Tuvaluan dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "UAH",
                            BaseNumber = 100,
                            FractionalUnit = "Kopiyka",
                            Name = "Ukrainian hryvnia",
                            Symbol = "₴"
                        },
                        new
                        {
                            CurrencyISOCode = "USD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "United States dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "UGX",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Ugandan shilling",
                            Symbol = "Sh"
                        },
                        new
                        {
                            CurrencyISOCode = "UYU",
                            BaseNumber = 100,
                            FractionalUnit = "Centésimo",
                            Name = "Uruguayan peso",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "UZS",
                            BaseNumber = 100,
                            FractionalUnit = "Tiyin",
                            Name = "Uzbekistani soʻm",
                            Symbol = "сўм"
                        },
                        new
                        {
                            CurrencyISOCode = "VES",
                            BaseNumber = 100,
                            FractionalUnit = "Céntimo",
                            Name = "Venezuelan bolívar soberano",
                            Symbol = "Bs."
                        },
                        new
                        {
                            CurrencyISOCode = "VND",
                            BaseNumber = 10,
                            FractionalUnit = "Hào",
                            Name = "Vietnamese đồng",
                            Symbol = "₫"
                        },
                        new
                        {
                            CurrencyISOCode = "XCD",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "Eastern Caribbean dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyISOCode = "XOF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "West African CFA franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyISOCode = "XAF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "Central African CFA franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            CurrencyISOCode = "XPF",
                            BaseNumber = 100,
                            FractionalUnit = "Centime",
                            Name = "CFP franc",
                            Symbol = "₣"
                        },
                        new
                        {
                            CurrencyISOCode = "WST",
                            BaseNumber = 100,
                            FractionalUnit = "Sene",
                            Name = "Samoan tālā",
                            Symbol = "T"
                        },
                        new
                        {
                            CurrencyISOCode = "VUV",
                            BaseNumber = 100,
                            FractionalUnit = "",
                            Name = "Vanuatu vatu",
                            Symbol = "Vt"
                        },
                        new
                        {
                            CurrencyISOCode = "ZAR",
                            BaseNumber = 100,
                            FractionalUnit = "Cent",
                            Name = "South African rand",
                            Symbol = "R"
                        },
                        new
                        {
                            CurrencyISOCode = "YER",
                            BaseNumber = 100,
                            FractionalUnit = "Fils",
                            Name = "Yemeni rial",
                            Symbol = "ر.ي"
                        },
                        new
                        {
                            CurrencyISOCode = "ZMW",
                            BaseNumber = 100,
                            FractionalUnit = "Ngwee",
                            Name = "Zambian kwacha",
                            Symbol = "ZK"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Planet", b =>
                {
                    b.Property<HierarchyId>("PlanetId")
                        .HasColumnType("hierarchyid");

                    b.Property<string>("PlanetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanetId");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            PlanetId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/"),
                            PlanetName = "Earth"
                        });
                });

            modelBuilder.Entity("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Country", b =>
                {
                    b.HasOne("MetaDataCoreServices.Core.Data.MetaDataDatabase.EntityFramework.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyISOCode");
                });
#pragma warning restore 612, 618
        }
    }
}
